### ISSUE TITLE
Removing optional models breaks the app

### ISSUE THREAD

**Issue by cngeru** [bharat-biradar/Google-Ml-Kit-plugin#101]
From the documentation and the issues raised in the repo I understand that we can strip away the models and assets on android to reduce bundle size. I am only using `face detection` in my app. I want to use `Google Play Api (face)` instead of the bundled models. I have tried removing the models from the app but the app breaks.

The models are `10 MB` in size which is huge considering they app can be shipped without them

I have already done this 

```
// android manifest

<meta-data
    android:name="com.google.firebase.ml.vision.DEPENDENCIES"
    android:value="face" />

// build.gradle

aaptOptions {
     ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:!hobbes.tflite:'
 }

packagingOptions {
  exclude 'lib/**/libtranslate_jni.so'
  exclude 'lib/**/libdigitalink.so'
  exclude 'lib/**/libxeno_native.so'
  exclude 'lib/**/libmlkitcommonpipeline.so'
  exclude 'lib/**/libbarhopper_v2.so'
  exclude 'lib/**/libclassifier_jni.so'
  exclude 'lib/**/libpredictor_jni.so'
  exclude 'lib/**/libtextclassifier3_jni_tclib.so'
  // exclude 'lib/**/libface_detector_v2_jni.so'
  exclude 'lib/**/libtensorflowlite_jni.so'
  exclude 'lib/**/liblanguage_id_jni.so'
}

```

and this breaks it

```
aaptOptions {
     ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:!hobbes.tflite:!models:'
}
```

Has anyone stripped the models and gotten successful results afterwards ? 
If yes, How?

**Comment by wazini-john** [comment]
@cngeru Did you get a fix ?

**Comment by radha1990kumari** [comment]
@cngeru  , I am getting this log ,(though after stripping unused resources it was working earlier ) :
```
W/DynamiteModule(10895): Local module descriptor class for com.google.mlkit.dynamite.face not found.
W/DynamiteModule(10895): Local module descriptor class for com.google.mlkit.dynamite.face not found.
W/zygote  (10895): Unsupported class loader
D/TransportRuntime.SQLiteEventStore(10895): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(10895): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
W/GooglePlayServicesUtil(10895): Google Play services out of date for com.example.facelist.  Requires 203390000 but found 11580470
W/GoogleApiManager(10895): The service for com.google.android.gms.common.internal.service.zap is not available: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}
W/zygote  (10895): Skipping duplicate class check due to unsupported classloader
D/EGL_emulation(10895): eglMakeCurrent: 0xa8f055a0: ver 3 0 (tinfo 0x9607f050)
D/EGL_emulation(10895): eglMakeCurrent: 0xa63150e0: ver 3 0 (tinfo 0x9607f0f0)
I/DynamiteModule(10895): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1101
I/DynamiteModule(10895): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1101
W/DynamiteModule(10895): Dynamite loader version < 2, falling back to loadModule2
D/TransportRuntime.SQLiteEventStore(10895): Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
W/zygote  (10895): Unsupported class loader
D/TransportRuntime.JobInfoScheduler(10895): Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
W/zygote  (10895): Skipping duplicate class check due to unsupported classloader
I/Vision  (10895): Loading library libmobile_vision_face.so
I/zygote  (10895): The ClassLoaderContext is a special shared library.
I/zygote  (10895): The ClassLoaderContext is a special shared library.
I/zygote  (10895): The ClassLoaderContext is a special shared library.
I/Vision  (10895): libmobile_vision_face.so library load status: false
I/Vision  (10895): Request download for engine face
D/LegacyFaceDelegate(10895): Request face optional module download.
D/TransportRuntime.SQLiteEventStore(10895): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
I/DynamiteModule(10895): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1101
I/DynamiteModule(10895): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1101
W/DynamiteModule(10895): Dynamite loader version < 2, falling back to loadModule2
I/Vision  (10895): Loading library libmobile_vision_face.so
I/Vision  (10895): libmobile_vision_face.so library load status: false
D/TransportRuntime.JobInfoScheduler(10895): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
W/GooglePlayServicesUtil(10895): Google Play services out of date for com.example.facelist.  Requires 203390000 but found 11580470
W/GoogleApiManager(10895): The service for com.google.android.gms.common.internal.service.zap is not available: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}
E/flutter (10895): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(FaceDetectorError, com.google.mlkit.common.MlKitException: Waiting for the face detection module to be downloaded. Please wait., null, null)
E/flutter (10895): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (10895): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (10895): <asynchronous suspension>
E/flutter (10895): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:344:35)
E/flutter (10895): <asynchronous suspension>
E/flutter (10895): #3      FaceDetector.processImage (package:google_ml_kit/src/vision/face_detector.dart:54:20)
E/flutter (10895): <asynchronous suspension>
E/flutter (10895): #4      AddingWidgetWithState.getImage (package:facelist/screens/temp.dart:144:32)
E/flutter (10895): <asynchronous suspension>
E/flutter (10895): #5      AddingWidgetWithState.mix (package:facelist/screens/temp.dart:42:24)
E/flutter (10895): <asynchronous suspension>
E/flutter (10895): 
D/TransportRuntime.SQLiteEventStore(10895): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(10895): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore(10895): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(10895): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...

```

**Comment by radha1990kumari** [comment]
@cngeru  , yes my app is working fine after removing these resources , plugin version `0.6.0` , try `flutter clean` and then build  the apk ,hopefully it will resolve the issue

**Comment by cngeru** [comment]
@radha1990kumari Have you excluded the models ? 
```
aaptOptions {
     ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:!hobbes.tflite:!models:'
}
```

**Comment by radha1990kumari** [comment]
@cngeru  ,I didn't include `!models` line but somehow  it was not included in my apk , I am using only face detection (to get bounding boxes around faces ) .My apk even didn't include `libface_detector_v2_jni.so' , but my new version has both and therby size is increased by 20mb . The only files which are present in old one but not in new one are `mlkit_odt_localizer` and `mlkit_odt_default_classifier` under assets. 
Heres the issue that I have created regarding the same :
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/108

**Comment by Pranet-Hiranandani** [comment]
Hi, you need to include the 'lib/**/libmlkitcommonpipeline.so' for the app to work. No libraries work without that. This is what I used for Custom Image Labelling. It reduced the APK size from around 300 MB to 60MB. 

`packagingOptions {
        exclude 'lib/**/libtranslate_jni.so'
        exclude 'lib/**/libdigitalink.so'
        exclude 'lib/**/libxeno_native.so'
        //exclude 'lib/**/libmlkitcommonpipeline.so'
        exclude 'lib/**/libbarhopper_v2.so'
        exclude 'lib/**/libpredictor_jni.so'
        exclude 'lib/**/libtextclassifier3_jni_tclib.so'
        exclude 'lib/**/libface_detector_v2_jni.so' //you can comment this out for face detection
        exclude 'lib/**/libtensorflowlite_jni.so'
        exclude 'lib/**/liblanguage_id_jni.so'
    }`

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

More details here: 

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
