### ISSUE TITLE
 Local module descriptor class for com.google.android.gms.vision.face not found.

### ISSUE THREAD

**Issue by radha1990kumari** [bharat-biradar/Google-Ml-Kit-plugin#104]
Upgraded from 0.6.0 to 0.7.0  and I got this error :
```
W/DynamiteModule( 5011): Local module descriptor class for com.google.mlkit.dynamite.face not found.
W/DynamiteModule( 5011): Local module descriptor class for com.google.mlkit.dynamite.face not found.
W/DynamiteModule( 5011): Local module descriptor class for com.google.mlkit.dynamite.face not found.
D/EGL_emulation( 5011): eglMakeCurrent: 0xa61886a0: ver 3 0 (tinfo 0x90096840)
D/EGL_emulation( 5011): eglMakeCurrent: 0xa6485ea0: ver 3 0 (tinfo 0xa6483880)
W/DynamiteModule( 5011): Local module descriptor class for com.google.android.gms.vision.face not found.
I/DynamiteModule( 5011): Considering local module com.google.android.gms.vision.face:0 and remote module com.google.android.gms.vision.face:0
W/DynamiteModule( 5011): Local module descriptor class for com.google.mlkit.dynamite.face not found.
W/DynamiteModule( 5011): Local module descriptor class for com.google.android.gms.vision.face not found.
I/DynamiteModule( 5011): Considering local module com.google.android.gms.vision.face:0 and remote module com.google.android.gms.vision.face:0
D/TransportRuntime.SQLiteEventStore( 5011): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
E/MobileVisionBase( 5011): Error preloading model resource
E/MobileVisionBase( 5011): com.google.mlkit.common.MlKitException: Waiting for the face module to be downloaded. Please wait.
E/MobileVisionBase( 5011): 	at com.google.mlkit.vision.face.internal.zza.zzd(com.google.android.gms:play-services-mlkit-face-detection@@16.2.0:10)
E/MobileVisionBase( 5011): 	at com.google.mlkit.vision.face.internal.zzh.load(com.google.android.gms:play-services-mlkit-face-detection@@16.2.0:1)
E/MobileVisionBase( 5011): 	at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@17.2.0:4)
E/MobileVisionBase( 5011): 	at com.google.mlkit.common.sdkinternal.zzm.run(Unknown Source:10)
E/MobileVisionBase( 5011): 	at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.2.0:2)
E/MobileVisionBase( 5011): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.2.0:4)
E/MobileVisionBase( 5011): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@17.2.0:1)
E/MobileVisionBase( 5011): 	at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
E/MobileVisionBase( 5011): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/MobileVisionBase( 5011): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/MobileVisionBase( 5011): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@17.2.0:2)
E/MobileVisionBase( 5011): 	at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
E/MobileVisionBase( 5011): 	at java.lang.Thread.run(Thread.java:764)
E/flutter ( 5011): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(FaceDetectorError, com.google.mlkit.common.MlKitException: Waiting for the face module to be downloaded. Please wait., null, null)
E/flutter ( 5011): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter ( 5011): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 5011): <asynchronous suspension>
E/flutter ( 5011): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:344:35)
E/flutter ( 5011): <asynchronous suspension>
E/flutter ( 5011): #3      FaceDetector.processImage (package:google_ml_kit/src/vision/face_detector.dart:54:20)
E/flutter ( 5011): <asynchronous suspension>
E/flutter ( 5011): #4      AddingWidgetWithState.getImage (package:facelist/screens/temp.dart:143:32)
E/flutter ( 5011): <asynchronous suspension>
E/flutter ( 5011): #5      AddingWidgetWithState.mix (package:facelist/screens/temp.dart:42:24)
E/flutter ( 5011): <asynchronous suspension>
E/flutter ( 5011): 
D/TransportRuntime.JobInfoScheduler( 5011): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore( 5011): Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler( 5011): Upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore( 5011): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler( 5011): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
```

**Comment by radha1990kumari** [comment]
`flutter clean` solved the issue
