### ISSUE TITLE
Local module descriptor class for com.google.mlkit.dynamite.face not found

### ISSUE THREAD

**Issue by radha1990kumari** [bharat-biradar/Google-Ml-Kit-plugin#106]
Running on emulator with version `0.7.0`  .
```
/DynamiteModule(11527): Local module descriptor class for com.google.mlkit.dynamite.face not found.
W/DynamiteModule(11527): Local module descriptor class for com.google.mlkit.dynamite.face not found.
W/zygote  (11527): Unsupported class loader
D/EGL_emulation(11527): eglMakeCurrent: 0xa8c144e0: ver 3 0 (tinfo 0x93e50030)
D/EGL_emulation(11527): eglMakeCurrent: 0xb0b65ac0: ver 3 0 (tinfo 0x93e07a50)
W/GooglePlayServicesUtil(11527): Google Play services out of date for com.example.dup_face.  Requires 203390000 but found 11580470
W/GoogleApiManager(11527): The service for com.google.android.gms.common.internal.service.zap is not available: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}
W/zygote  (11527): Skipping duplicate class check due to unsupported classloader
I/DynamiteModule(11527): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1101
I/DynamiteModule(11527): Selected remote version of com.google.android.gms.vision.dynamite, version >= 1101
W/DynamiteModule(11527): Dynamite loader version < 2, falling back to loadModule2
D/TransportRuntime.SQLiteEventStore(11527): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(11527): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
W/zygote  (11527): Unsupported class loader
D/TransportRuntime.SQLiteEventStore(11527): Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(11527): Scheduling upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) with jobId=1271538980 in 643158ms(Backend next call timestamp 1627973052471). Attempt 1
W/zygote  (11527): Skipping duplicate class check due to unsupported classloader
I/Vision  (11527): Loading library libmobile_vision_face.so
I/zygote  (11527): The ClassLoaderContext is a special shared library.
I/chatty  (11527): uid=10082(com.example.dup_face) pool-17-thread- identical 1 line
I/zygote  (11527): The ClassLoaderContext is a special shared library.
I/pittpatt(11527): wrapper.cc:442] JNI_OnLoad successful
I/Vision  (11527): libmobile_vision_face.so library load status: true
D/TransportRuntime.SQLiteEventStore(11527): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler(11527): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
E/flutter (11527): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(FaceDetectorError, com.google.mlkit.common.MlKitException: Internal error has occurred when executing ML Kit tasks, null, null)
E/flutter (11527): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (11527): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (11527): <asynchronous suspension>
E/flutter (11527): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:344:35)
E/flutter (11527): <asynchronous suspension>
E/flutter (11527): #3      FaceDetector.processImage (package:google_ml_kit/src/vision/face_detector.dart:54:20)
E/flutter (11527): <asynchronous suspension>
E/flutter (11527): #4      AddingWidgetWithState.getImage (package:facelist/screens/temp.dart:144:32)
E/flutter (11527): <asynchronous suspension>
E/flutter (11527): #5      AddingWidgetWithState.mix (package:facelist/screens/temp.dart:42:24)
E/flutter (11527): <asynchronous suspension>
E/flutter (11527): 

```

**Comment by radha1990kumari** [comment]
Downgrading  version to `0.6.0` seems to solve the issue .

**Comment by momoDragon** [comment]
Same issue here. downgrading to 0.6.0 worked for me. should this issue be reopened? because 0.7.0 is not working as intended

**Comment by fbernaly** [comment]
We released a new version of [google_ml_kit](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit) in which we have split all the plugins in multiple plugins to avoid removing the models for API you are not using, go to our readme and start using the new plugin you need.

More details here:

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
