### ISSUE TITLE
[ANDROID] App is working properly on debug mode but not works for profile mode.

### ISSUE THREAD

**Issue by unoravi** [bharat-biradar/Google-Ml-Kit-plugin#174]
I have created one cameraView demo and it's working properly with --debug mode. But when running the same on --profile or --release mode, it's facing an issue (hangs/crash) while loading cameraView.

Flutter Doctor :
```
flutter doctor -v
[√] Flutter (Channel dev, 2.6.0-11.0.pre, on Microsoft Windows [Version 10.0.18363.1016], locale en-CA)
    • Flutter version 2.6.0-11.0.pre at C:\Program Files\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b330ddbed (2 months ago), 2021-09-16 17:29:58 -0700
    • Engine revision 5b81c6d615
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\street\AppData\Local\Android\sdk
    • Platform android-31, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\street\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • SM M305F (mobile) • 3200162f47a12647 • android-arm64 • Android 10 (API 29)
    • Windows (desktop) • windows          • windows-x64   • Microsoft Windows [Version 10.0.18363.1016]
```

Exception Logs : 
```
[   +1 ms] I/CameraManagerGlobal(23896): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.example.demoapp API Level 2
[  +72 ms] E/MethodChannel#plugins.flutter.io/camera(23896): Failed to handle method call
[   +1 ms] E/MethodChannel#plugins.flutter.io/camera(23896): java.lang.NullPointerException: Attempt to invoke virtual method
'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference
[  +15 ms] E/MethodChannel#plugins.flutter.io/camera(23896):    at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:291)
[   +9 ms] E/MethodChannel#plugins.flutter.io/camera(23896):    at io.flutter.plugins.camera.Camera.createCaptureSession(Camera.java:281)
[   +1 ms] E/MethodChannel#plugins.flutter.io/camera(23896):    at io.flutter.plugins.camera.Camera.startPreviewWithImageStream(Camera.java:1099)
[        ] E/MethodChannel#plugins.flutter.io/camera(23896):    at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:251)
[   +2 ms] E/MethodChannel#plugins.flutter.io/camera(23896):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)   
[  +23 ms] E/MethodChannel#plugins.flutter.io/camera(23896):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
[  +41 ms] E/MethodChannel#plugins.flutter.io/camera(23896):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:869)
[   +2 ms] E/MethodChannel#plugins.flutter.io/camera(23896):    at android.os.MessageQueue.nativePollOnce(Native Method)
[  +22 ms] E/MethodChannel#plugins.flutter.io/camera(23896):    at android.os.MessageQueue.next(MessageQueue.java:336)
[   +2 ms] E/MethodChannel#plugins.flutter.io/camera(23896):    at android.os.Looper.loop(Looper.java:197)
[        ] E/MethodChannel#plugins.flutter.io/camera(23896):    at android.app.ActivityThread.main(ActivityThread.java:7807)
[   +1 ms] E/MethodChannel#plugins.flutter.io/camera(23896):    at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/camera(23896):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[   +1 ms] E/MethodChannel#plugins.flutter.io/camera(23896):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
[        ] I/Choreographer(23896): Skipped 228 frames!  The application may be doing too much work on its main thread.
[   +1 ms] E/flutter (23896): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: CameraException(error, Attempt to invoke virtual method
'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference)
[   +1 ms] E/flutter (23896): #0      CameraController.startImageStream (package:camera/src/camera_controller.dart:388)
[        ] E/flutter (23896): <asynchronous suspension>
[  +26 ms] E/flutter (23896): 
[   +2 ms] I/flutter (23896): Another exception was thrown: Instance of 'ErrorSummary'
[        ] I/flutter (23896): Another exception was thrown: Instance of 'ErrorSummary'
[   +1 ms] I/flutter (23896): Another exception was thrown: Instance of 'ErrorSummary'
[        ] D/ViewRootImpl@cd7d633[MainActivity](23896): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=9 res=0x3 s={true 520294756352} 
ch=false
[   +2 ms] I/Camera  (23896): [FPS Range Available] is:[10, 10]
[  +16 ms] I/Camera  (23896): [FPS Range Available] is:[15, 15]
[   +2 ms] I/Camera  (23896): [FPS Range Available] is:[15, 20]
[  +18 ms] I/Camera  (23896): [FPS Range Available] is:[20, 20]
[        ] I/Camera  (23896): [FPS Range Available] is:[24, 24]
[   +1 ms] I/Camera  (23896): [FPS Range Available] is:[8, 30]
[        ] I/Camera  (23896): [FPS Range Available] is:[10, 30]
[   +1 ms] I/Camera  (23896): [FPS Range Available] is:[15, 30]
[        ] I/Camera  (23896): [FPS Range Available] is:[30, 30]
[   +1 ms] I/Camera  (23896): [FPS Range] is:[8, 30]
[        ] D/SensorManager(23896): registerListener :: 0, LSM6DSL Accelerometer, 200000, 0,  
[   +2 ms] W/Camera  (23896): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
[   +5 ms] I/CameraManagerGlobal(23896): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.example.demoapp API Level 2
[   +9 ms] I/CameraManagerGlobal(23896): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.example.demoapp API Level 2
[   +3 ms] D/ViewRootImpl@cd7d633[MainActivity](23896): MSG_RESIZED_REPORT: frame=(0,0,1080,2340) ci=(0,83,0,126) vi=(0,83,0,126) or=1
[  +15 ms] D/ViewRootImpl@cd7d633[MainActivity](23896): MSG_WINDOW_FOCUS_CHANGED 1 1
[        ] D/InputMethodManager(23896): prepareNavigationBarInfo() DecorView@fd1bb31[MainActivity]
[  +19 ms] D/InputMethodManager(23896): getNavigationBarColor() -855310
[ +273 ms] I/CameraManagerGlobal(23896): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_ACTIVE for client com.example.demoapp API Level 2
[  +21 ms] I/CameraManagerGlobal(23896): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.example.demoapp API Level 2
[ +175 ms] D/ViewRootImpl@cd7d633[MainActivity](23896): ViewPostIme pointer 0
[   +5 ms] D/ViewRootImpl@cd7d633[MainActivity](23896): ViewPostIme pointer 1
[ +269 ms] I/CameraManagerGlobal(23896): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_ACTIVE for client com.example.demoapp API Level 2
[  +16 ms] I/CameraManagerGlobal(23896): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.example.demoapp API Level 2
[ +167 ms] W/example.demoap(23896): Long monitor contention with owner main (23896) at void
android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSessionInternal(android.hardware.camera2.params.InputConfiguration, java.util.List,
android.hardware.camera2.CameraCaptureSession$StateCallback, java.util.concurrent.Executor, int, android.hardware.camera2.CaptureRequest)(CameraDeviceImpl.java:643)    
waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for    
160ms
[  +35 ms] V/FaceDetectorV2Jni(23896): detectFacesImageByteArray.start()
[   +1 ms] W/example.demoap(23896): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[  +26 ms] D/TransportRuntime.SQLiteEventStore(23896): Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
[  +30 ms] D/TransportRuntime.JobInfoScheduler(23896): Upload for context TransportContext(cct, DEFAULT,
MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
[   +4 ms] V/FaceDetectorV2Jni(23896): detectFacesImageByteArray.end()
[   +1 ms] V/FaceDetectorV2Jni(23896): detectFacesImageByteArray.start()
[  +54 ms] V/FaceDetectorV2Jni(23896): detectFacesImageByteArray.end()
[   +7 ms] D/ViewRootImpl@cd7d633[MainActivity](23896): MSG_WINDOW_FOCUS_CHANGED 0 1
[   +2 ms] D/InputMethodManager(23896): prepareNavigationBarInfo() DecorView@fd1bb31[MainActivity]
[   +1 ms] D/InputMethodManager(23896): getNavigationBarColor() -855310
[   +6 ms] I/flutter (23896): Another exception was thrown: Instance of 'ErrorSummary'
[  +13 ms] I/chatty  (23896): uid=10257(com.example.demoapp) 1.ui identical 1 line
[  +22 ms] I/flutter (23896): Another exception was thrown: Instance of 'ErrorSummary'
```

**Comment by unoravi** [comment]
Any Updates ?

**Comment by fbernaly** [comment]
Try the latest version.

Also note that `google_ml_kit` has been split in multiples plugins, to avoid adding unnecessary dependencies to your project.

More details here:
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
- https://github.com/bharat-biradar/Google-Ml-Kit-plugin
