### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent

### ISSUE THREAD

**Issue by xang555** [bharat-biradar/Google-Ml-Kit-plugin#192]
I test this plugin in android 12 but the app crashes immediately when I try to remove this plugin everything is well

## my environment information

- Google-Ml-Kit-plugin version `^0.7.3`
- Test on android 12
- set `compileSdkVersion 31`, `minSdkVersion 23`, `targetSdkVersion 31`
- flutter `2.8.1`

full error

```
E/AndroidRuntime(10367): FATAL EXCEPTION: pool-11-thread-1
E/AndroidRuntime(10367): Process: example.com.myapp, PID: 10367
E/AndroidRuntime(10367): java.lang.IllegalArgumentException: example.com.myapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(10367): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(10367):        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E/AndroidRuntime(10367):        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
E/AndroidRuntime(10367):        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
E/AndroidRuntime(10367):        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
E/AndroidRuntime(10367):        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
E/AndroidRuntime(10367):        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
E/AndroidRuntime(10367):        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
E/AndroidRuntime(10367):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10367):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10367):        at java.lang.Thread.run(Thread.java:920)
```

**Comment by xang555** [comment]
Fixed

add the following

```
    // For apps targeting Android S+, add the following
    implementation 'androidx.work:work-runtime:2.7.0-alpha04'
```

ref: [ml-kit issues](https://developers.google.com/ml-kit/known-issues)

**Comment by jonsamwell** [comment]
Also keeping the targetSdkVersion to 30 for now works
