### ISSUE TITLE
works only up to com.google.mlkit:barcode-scanning:17.0.0

### ISSUE THREAD

**Issue by haraldkofler** [bharat-biradar/Google-Ml-Kit-plugin#209]
If defining in build.gradle a mlkit:barcode-scanning newer than 17.0.0 the lib crashes with a ClassNotFound exception (Barcode).

**works:**

```
dependencies {
    ...  
    implementation 'com.google.mlkit:barcode-scanning:17.0.0'
    ...
```

**does not work:**

```
dependencies {
    ...  
    implementation 'com.google.mlkit:barcode-scanning:17.0.1'
    ...
```

produces the following exception:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/barcode/Barcode;
	at com.google_ml_kit.vision.BarcodeDetector$2.onSuccess(BarcodeDetector.java:87)
	at com.google_ml_kit.vision.BarcodeDetector$2.onSuccess(BarcodeDetector.java:83)
	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.mlkit.vision.barcode.Barcode" on path: DexPathList[[zip file "/data/app/com.testapp-uquMC7eFgkuBxIjNQefcqw==/base.apk"],nativeLibraryDirectories=[/data/app/com.testapp-uquMC7eFgkuBxIjNQefcqw==/lib/x86, /data/app/com.testapp-uquMC7eFgkuBxIjNQefcqw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 10 more
```

**Comment by fbernaly** [comment]
@haraldkofler: try our new plugin: `google_mlkit_barcode_scanning` it is using the latest: `com.google.mlkit:barcode-scanning:17.0.2`:  
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_barcode_scanning/android/build.gradle

 More info here:

https://pub.dev/packages/google_mlkit_barcode_scanning

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_barcode_scanning

https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
