### ISSUE TITLE
getting this weird platform exception & NoClassDefFoundError whenever I tried to update google ml kit

### ISSUE THREAD

**Issue by ryanaidilp** [bharat-biradar/Google-Ml-Kit-plugin#221]
I got this weird error where my face detector app working just fine on the beginning and then crashed after Im running pub update.
 
here's some thing I notice
```
PlatformException(error, Image dimension, ByteBuffer size and format don't match. Please check if the ByteBuffer is in the decalred format., null, java.lang.IllegalArgumentException: Image dimension, ByteBuffer size and format don't match. Please check if the ByteBuffer is in the decalred format.
	at com.google.android.gms.common.internal.Preconditions.checkArgument(com.google.android.gms:play-services-basement@@18.0.0:2)
	at com.google.mlkit.vision.common.InputImage.<init>(com.google.mlkit:vision-common@@17.0.0:8)
	at com.google.mlkit.vision.common.InputImage.fromByteArray(com.google.mlkit:vision-common@@17.0.0:2)
	at com.b.biradar.google_ml_kit.vision.InputImageConverter.getInputImageFromData(InputImageConverter.java:36)
	at com.b.biradar.google_ml_kit.vision.FaceDetector.handleDetection(FaceDetector.java:62)
	at com.b.biradar.google_ml_kit.vision.FaceDetector.onMethodCall(FaceDetector.java:51)
	at com.b.biradar.google_ml_kit.MlKitMethodCallHandler.onMethodCall(MlKitMethodCallHandler.java:62)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
)
```

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/common/internal/Detector;
E/AndroidRuntime(29779): 	at com.b.biradar.google_ml_kit.MlKitMethodCallHandler.<init>(MlKitMethodCallHandler.java:34)
E/AndroidRuntime(29779): 	at com.b.biradar.google_ml_kit.GoogleMlKitPlugin.onAttachedToEngine(GoogleMlKitPlugin.java:28)
E/AndroidRuntime(29779): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:145)
E/AndroidRuntime(29779): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:104)
E/AndroidRuntime(29779): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29779): 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
E/AndroidRuntime(29779): 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1009)
E/AndroidRuntime(29779): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:199)
E/AndroidRuntime(29779): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459)
E/AndroidRuntime(29779): 	at android.app.Activity.performCreate(Activity.java:7969)
E/AndroidRuntime(29779): 	at android.app.Activity.performCreate(Activity.java:7958)
E/AndroidRuntime(29779): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
E/AndroidRuntime(29779): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3505)
E/AndroidRuntime(29779): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3689)
E/AndroidRuntime(29779): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(29779): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
E/AndroidRuntime(29779): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
E/AndroidRuntime(29779): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
E/AndroidRuntime(29779): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(29779): 	at android.os.Looper.loop(Looper.java:227)
E/AndroidRuntime(29779): 	at android.app.ActivityThread.main(ActivityThread.java:7822)
E/AndroidRuntime(29779): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29779): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(29779): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
E/AndroidRuntime(29779): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.mlkit.vision.common.internal.Detector" on path: DexPathList[[zip file "/data/app/com.banuacoders.donggala.siap-dDHCwvOeRx_HKGaNiIvxNw==/base.apk"],nativeLibraryDirectories=[/data/app/com.banuacoders.donggala.siap-dDHCwvOeRx_HKGaNiIvxNw==/lib/arm64, /data/app/com.banuacoders.donggala.siap-dDHCwvOeRx_HKGaNiIvxNw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
E/AndroidRuntime(29779): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime(29779): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(29779): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(29779): 	... 24 more
```

I'm using the latest version and trying to downgrade it to version 5 and still got the same error

**Comment by X-SLAYER** [comment]
can you show a part of your code that u used?

**Comment by ryanaidilp** [comment]
@X-SLAYER okay,

here's some of my code related to google ml kit

- camera_service.dart
```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:google_ml_kit/google_ml_kit.dart';

class CameraService {
  CameraController? _cameraController;
  CameraController? get cameraController => _cameraController;

  InputImageRotation? _cameraRotation;
  InputImageRotation? get cameraRotation => _cameraRotation;

  String? _imagePath;
  String? get imagePath => _imagePath;

  Future<void> initialize() async {
    if (_cameraController != null) return;
    CameraDescription description = await _getCameraDescription();
    await _setupCameraController(description: description);
    _cameraRotation = rotationIntToImageRotation(
      description.sensorOrientation,
    );
  }

  Future<CameraDescription> _getCameraDescription() async {
    List<CameraDescription> cameras = await availableCameras();
    return cameras.firstWhere((CameraDescription camera) =>
        camera.lensDirection == CameraLensDirection.front);
  }

  Future _setupCameraController({
    required CameraDescription description,
  }) async {
    _cameraController = CameraController(
      description,
      ResolutionPreset.high,
      enableAudio: false,
    );
    await _cameraController?.initialize();
  }

  InputImageRotation rotationIntToImageRotation(int rotation) {
    switch (rotation) {
      case 90:
        return InputImageRotation.Rotation_90deg;
      case 180:
        return InputImageRotation.Rotation_180deg;
      case 270:
        return InputImageRotation.Rotation_270deg;
      default:
        return InputImageRotation.Rotation_0deg;
    }
  }

  Future<XFile?> takePicture() async {
    assert(_cameraController != null, 'Camera controller not initialized');
    await _cameraController?.stopImageStream();
    XFile? file = await _cameraController?.takePicture();
    _imagePath = file?.path;
    return file;
  }

  Size getImageSize() {
    assert(_cameraController != null, 'Camera controller not initialized');
    assert(
        _cameraController!.value.previewSize != null, 'Preview size is null');
    return Size(
      _cameraController!.value.previewSize!.height,
      _cameraController!.value.previewSize!.width,
    );
  }

  dispose() async {
    await _cameraController?.dispose();
    _cameraController = null;
  }
}

```
- ml_vision_service
```dart
import 'dart:math';
import 'dart:typed_data';

import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:google_ml_kit/google_ml_kit.dart';
import 'package:image/image.dart' as img;
import 'package:siap_donggala_app/app/core/utils/helpers.dart';
import 'package:tflite_flutter/tflite_flutter.dart';

class MlVisionService{
  Interpreter? _interpreter;
  double threshold = 0.5;

  List _predictedData = [];
  List get predictedData => _predictedData;

  Future initialize() async {
    try {
      final gpuDelegateV2 = GpuDelegateV2(
        options: GpuDelegateOptionsV2(
          isPrecisionLossAllowed: false,
          inferencePreference: TfLiteGpuInferenceUsage.fastSingleAnswer,
          inferencePriority1: TfLiteGpuInferencePriority.minLatency,
          inferencePriority2: TfLiteGpuInferencePriority.auto,
          inferencePriority3: TfLiteGpuInferencePriority.auto,
        ),
      );

      var interpreterOptions = InterpreterOptions()..addDelegate(gpuDelegateV2);
      _interpreter = await Interpreter.fromAsset(
        'ml_model/mobilefacenet.tflite',
        options: interpreterOptions,
      );
    } catch (e) {
      print(e.toString());
      debugPrint(e.toString());
    }
  }

  void setCurrentPrediction(CameraImage image, Face? face) {
    if (_interpreter == null) throw Exception('Interpreter is null!');
    if (face == null) throw Exception('Face is null!');

    if (_predictedData.isNotEmpty) {
      _predictedData.clear();
    }

    /// crops the face from the image and transforms it to an array of data
    List input = _preProcess(image, face);

    /// then reshapes input and ouput to model format 🧑‍🔧
    input = input.reshape([1, 112, 112, 3]);
    List output = List.generate(1, (index) => List.filled(192, 0));

    /// runs and transforms the data 🤖
    _interpreter?.run(input, output);
    output = output.reshape([192]);

    _predictedData.addAll(List.from(output));
  }

  List _preProcess(CameraImage image, Face face) {
    img.Image croppedImage = _cropFace(image, face);
    img.Image _image = img.copyResizeCropSquare(croppedImage, 112);

    // transforms the cropped face to array data
    Float32List imageAsList = imageToByteListFloat32(_image);
    return imageAsList;
  }

  img.Image _cropFace(CameraImage image, Face face) {
    img.Image convertedImage = _convertCameraImage(image);
    double x = face.boundingBox.left - 10.0;
    double y = face.boundingBox.top - 10.0;
    double w = face.boundingBox.width + 10.0;
    double h = face.boundingBox.height + 10.0;
    return img.copyCrop(
        convertedImage, x.round(), y.round(), w.round(), h.round());
  }

  img.Image _convertCameraImage(CameraImage image) {
    var _img = convertToImage(image);
    var img1 = img.copyRotate(_img, -90);
    return img1;
  }

  Float32List imageToByteListFloat32(img.Image image) {
    /// input size = 112
    var convertedBytes = Float32List(1 * 112 * 112 * 3);
    var buffer = Float32List.view(convertedBytes.buffer);
    int pixelIndex = 0;

    for (var i = 0; i < 112; i++) {
      for (var j = 0; j < 112; j++) {
        var pixel = image.getPixel(j, i);

        /// mean: 128
        /// std: 128
        buffer[pixelIndex++] = (img.getRed(pixel) - 128) / 128;
        buffer[pixelIndex++] = (img.getGreen(pixel) - 128) / 128;
        buffer[pixelIndex++] = (img.getBlue(pixel) - 128) / 128;
      }
    }
    return convertedBytes.buffer.asFloat32List();
  }

  double _euclideanDistance(List e1, List e2) {
    double sum = 0.0;
    for (int i = 0; i < e1.length; i++) {
      sum += pow((e1[i] - e2[i]), 2);
    }
    return sqrt(sum);
  }

  void setPredictedData(value) {
    _predictedData = value;
  }

  bool predict(List data) {
    /// if no faces saved
    if (data.isEmpty) return false;
    double minDist = 999;
    double currDist = 0.0;

    currDist = _euclideanDistance(data, predictedData);

    printError(info: e.toString());

    return currDist <= threshold && currDist < minDist;
  }

  void dispose() {
    //
  }
}

```

- face_detector_service.dart
```dart
import 'package:camera/camera.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:google_ml_kit/google_ml_kit.dart';
import '/app/data/services/camera_service.dart';

class FaceDetectorService{
  final CameraService _cameraService = GetInstance().find<CameraService>();

  late FaceDetector _faceDetector;

  FaceDetector get faceDetector => _faceDetector;

  List<Face> _faces = [];

  List<Face> get faces => _faces;

  bool get faceDetected => _faces.isNotEmpty;

  void initialize() {
    _faceDetector = GoogleMlKit.vision.faceDetector(
      const FaceDetectorOptions(
        mode: FaceDetectorMode.accurate,
        enableClassification: true,
      ),
    );
  }

  Future<void> detectFacesFromImage(CameraImage image) async {
    InputImageData _inputImageData = InputImageData(
      imageRotation:
          _cameraService.cameraRotation ?? InputImageRotation.Rotation_0deg,
      inputImageFormat:
          InputImageFormatMethods.fromRawValue(image.format.raw) ??
              InputImageFormat.NV21,
      size:
          Size(image.planes[0].bytesPerRow.toDouble(), image.height.toDouble()),
      planeData: image.planes.map(
        (Plane plane) {
          return InputImagePlaneMetadata(
            bytesPerRow: plane.bytesPerRow,
            height: image.height,
            width: image.width,
          );
        },
      ).toList(),
    );

    InputImage _inputImage = InputImage.fromBytes(
      bytes: image.planes.first.bytes,
      inputImageData: _inputImageData,
    );

    print('inputImageData: ${_inputImage.inputImageData?.getMetaData()}');

    _faces = await _faceDetector.processImage(_inputImage);
  }

  dispose() {
    _faceDetector.close();
  }
}

```

after some debugging I notice that my code never get pass this line in face_detector_service.dart
```dart
  _faces = await _faceDetector.processImage(_inputImage);
```

**Comment by X-SLAYER** [comment]
I think the problem is with the bytes passed to  `InputImage.fromBytes` 
try to change this 
```dart
InputImage _inputImage = InputImage.fromBytes(
      bytes: image.planes.first.bytes,
      inputImageData: _inputImageData,
    );
```
to this 

```dart
final WriteBuffer allBytes = WriteBuffer();
 for (Plane plane in image.planes) {
          allBytes.putUint8List(plane.bytes);
        }
 final bytes = allBytes.done().buffer.asUint8List();
 InputImage _inputImage = InputImage.fromBytes(
      bytes: bytes,
      inputImageData: _inputImageData,
    );
```

**Comment by ryanaidilp** [comment]
@X-SLAYER okay, I'll try it

**Comment by ryanaidilp** [comment]
@X-SLAYER now i got another error and my app keep crashing whenever I'm trying to open the camera to scan face.
here's the log 

```
2022-04-21 21:19:31.194 26206-26206/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.banuacoders.donggala.siap, PID: 26206
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/common/internal/Detector;
        at com.b.biradar.google_ml_kit.MlKitMethodCallHandler.<init>(MlKitMethodCallHandler.java:34)
        at com.b.biradar.google_ml_kit.GoogleMlKitPlugin.onAttachedToEngine(GoogleMlKitPlugin.java:28)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:145)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:104)
        at java.lang.reflect.Method.invoke(Native Method)
        at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
        at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1009)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:199)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459)
        at android.app.Activity.performCreate(Activity.java:7969)
        at android.app.Activity.performCreate(Activity.java:7958)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3505)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3689)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7822)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.mlkit.vision.common.internal.Detector" on path: DexPathList[[zip file "/data/app/com.banuacoders.donggala.siap-O1LAJgHJ36k5WUFYLQfeAg==/base.apk"],nativeLibraryDirectories=[/data/app/com.banuacoders.donggala.siap-O1LAJgHJ36k5WUFYLQfeAg==/lib/arm64, /data/app/com.banuacoders.donggala.siap-O1LAJgHJ36k5WUFYLQfeAg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.b.biradar.google_ml_kit.MlKitMethodCallHandler.<init>(MlKitMethodCallHandler.java:34) 
        at com.b.biradar.google_ml_kit.GoogleMlKitPlugin.onAttachedToEngine(GoogleMlKitPlugin.java:28) 
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:145) 
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:104) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80) 
        at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1009) 
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:199) 
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459) 
        at android.app.Activity.performCreate(Activity.java:7969) 
        at android.app.Activity.performCreate(Activity.java:7958) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3505) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3689) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:227) 
        at android.app.ActivityThread.main(ActivityThread.java:7822) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026) 
```

**Comment by ryanaidilp** [comment]
here's my gradle and manifest file 

- *android/build.gradle*
```gradle
buildscript {
    ext.kotlin_version = '1.6.21'
    repositories {
        google()
        mavenCentral()
        maven { url 'https://plugins.gradle.org/m2/' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.14.0, 0.99.99]'
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

- *android/app/build.gradle*
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply from: project(':flutter_config').projectDir.getPath() + "/dotenv.gradle"
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if(keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    aaptOptions {
        noCompress "tflite"
        noCompress "lite"
    }

    compileSdkVersion 31

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.banuacoders.donggala.siap"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            aaptOptions {
                ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:!hobbes.tflite:'
            }
        }

        debug {
            signingConfig signingConfigs.debug
            aaptOptions {
                ignoreAssetsPattern '!mlkit_pose:!mlkit_label_default_model:!hobbes.tflite:'
            }
        }
    }

    packagingOptions {
        exclude 'lib/**/libtranslate_jni.so'
        exclude 'lib/**/libdigitalink.so'
        exclude 'lib/**/libxeno_native.so'
        exclude 'lib/**/libmlkitcommonpipeline.so'
        exclude 'lib/**/libbarhopper_v2.so'
        exclude 'lib/**/libclassifier_jni.so'
        exclude 'lib/**/libpredictor_jni.so'
        exclude 'lib/**/libtextclassifier3_jni_tclib.so'
//         exclude 'lib/**/libface_detector_v2_jni.so'
//        exclude 'lib/**/libtensorflowlite_jni.so'
        exclude 'lib/**/liblanguage_id_jni.so'
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:29.0.1')
    implementation 'com.google.firebase:firebase-analytics'
}

apply plugin: 'com.google.firebase.crashlytics'
```

- *AndroidManifest.xml
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.banuacoders.donggala.siap">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.VIBRATE" />
   <application
        android:label="SiAP Donggala"
        android:name="${applicationName}"
       android:requestLegacyExternalStorage="true"
       android:roundIcon="@mipmap/ic_launcher_round"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- Specifies an Android theme to apply to this Activity as soon as
                 the Android process has started. This theme is visible to the user
                 while the Flutter UI initializes. After that, this theme continues
                 to determine the Window background behind the Flutter UI. -->
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
       <meta-data
           android:name="com.google.mlkit.vision.DEPENDENCIES"
           android:value="face" />
    </application>
</manifest>

```

are there anything wrong with my configuration?

**Comment by X-SLAYER** [comment]
try to use the last version 0.8.0

**Comment by fbernaly** [comment]
@ryanaidilp: if you are using only face detection use `google_mlkit_face_detection: ^0.0.1` instead: 
https://pub.dev/packages/google_mlkit_face_detection
 google_mlkit_face_detection is ours as well, and we split all the API to their corresponding plugin to avoid adding unnecessary dependencies to your project.

Now google_ml_kit v0.8.0 is just an umbrella plugin including all the plugins.

**Comment by ryanaidilp** [comment]
@fbernaly I'm updating my app to use this plugin and it worked now. Thanks.

**Comment by definev** [comment]
I'm facing the same issue with the latest version (0.3.0)

**Comment by fbernaly** [comment]
@definev : share your logs, please

**Comment by definev** [comment]
> @definev : share your logs, please

I fix it, but it's pretty hard to spot where I'm wrong. I don't transform properly the raw image from `CameraImage` i get from `camera` packages to `InputImage` which `processImage` function in `FaceDetector` need. I think you should create a helper plugin that transforms `CameraImage` to `InputImage`. I see the example app and get this code to transform the image, can you wrap this into a plugin for other people?

```dart
  final WriteBuffer allBytes = WriteBuffer();
  for (final Plane plane in image.planes) {
    allBytes.putUint8List(plane.bytes);
  }
  final bytes = allBytes.done().buffer.asUint8List();

  final Size imageSize = Size(image.width.toDouble(), image.height.toDouble());

  final camera = description;
  final imageRotation =
      InputImageRotationValue.fromRawValue(camera.sensorOrientation) ??
          InputImageRotation.rotation0deg;

  final inputImageFormat =
      InputImageFormatValue.fromRawValue(image.format.raw) ??
          InputImageFormat.nv21;

  final planeData = image.planes.map(
    (Plane plane) {
      return InputImagePlaneMetadata(
        bytesPerRow: plane.bytesPerRow,
        height: plane.height,
        width: plane.width,
      );
    },
  ).toList();

  final inputImageData = InputImageData(
    size: imageSize,
    imageRotation: imageRotation,
    inputImageFormat: inputImageFormat,
    planeData: planeData,
  );

  final inputImage =
      InputImage.fromBytes(bytes: bytes, inputImageData: inputImageData);
```

**Comment by fbernaly** [comment]
@definev : I am glad you found a solution for your issue. Thanks for clarifying that the issue was in the process of getting an `InputImage` from `CameraImage` and not it our plugin.

We have documented that extensively in our README, and that code your shared is in both the example app and the README: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_commons#usage

Thanks for the suggestion of wrapping this code in a plugin, but we think it is better to have it in the README, that could leave the door open to use other options/plugins to get the input image rather than endorsing only Camera plugin.
