### ISSUE TITLE
E/ModelUtils( 9441): Failed to open model file

### ISSUE THREAD

**Issue by parkerhutchinson** [bharat-biradar/Google-Ml-Kit-plugin#237]
I can only assume I'm doing this right since there is no documentation around using local label options and where someone would store their custom tflite model. But I'm pretty sure this would be all I need to load one in and have it working yet: 
```
  final LocalLabelerOptions options = LocalLabelerOptions(
      confidenceThreshold: 0.5,
      type: LocalModelType.asset,
      customModelPath: 'assets/ml/image_classifier.tflite');

  final imageLabeler = GoogleMlKit.vision.imageLabeler(options);
  final inputImage = InputImage.fromFilePath(imageFile);

  final List<ImageLabel> labels = await imageLabeler.processImage(inputImage);
```
**pubspec.yaml**
```
assets:
  - assets/ml/
```
**output:** 
```
E/ModelUtils( 9441): Failed to open model file
E/ModelUtils( 9441): java.io.FileNotFoundException: assets/ml/image_classifier.tflite
E/ModelUtils( 9441): 	at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
E/ModelUtils( 9441): 	at android.content.res.AssetManager.openFd(AssetManager.java:905)
E/ModelUtils( 9441): 	at com.google.mlkit.common.internal.model.ModelUtils.getModelLoggingInfo(com.google.mlkit:common@@18.1.0:6)
E/ModelUtils( 9441): 	at com.google.mlkit.vision.label.custom.internal.zzf.zzc(com.google.mlkit:image-labeling-custom@@17.0.1:2)
E/ModelUtils( 9441): 	at com.google.mlkit.vision.label.custom.internal.zze.tryLoad(com.google.mlkit:image-labeling-custom@@17.0.1:1)
E/ModelUtils( 9441): 	at com.google.mlkit.common.sdkinternal.model.CustomModelLoader.load(com.google.mlkit:common@@18.1.0:3)
E/ModelUtils( 9441): 	at com.google.mlkit.vision.label.custom.internal.zzf.load(com.google.mlkit:image-labeling-custom@@17.0.1:2)
E/ModelUtils( 9441): 	at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.1.0:4)
E/ModelUtils( 9441): 	at com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10)
E/ModelUtils( 9441): 	at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@18.1.0:2)
E/ModelUtils( 9441): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.1.0:4)
E/ModelUtils( 9441): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.1.0:1)
E/ModelUtils( 9441): 	at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
E/ModelUtils( 9441): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ModelUtils( 9441): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ModelUtils( 9441): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.1.0:2)
E/ModelUtils( 9441): 	at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
E/ModelUtils( 9441): 	at java.lang.Thread.run(Thread.java:920)
```
which then causes more errors:
```
E/MobileVisionBase( 9441): Error preloading model resource
E/MobileVisionBase( 9441): com.google.mlkit.common.MlKitException: Failed to initialize detector.
E/MobileVisionBase( 9441): 	at com.google.mlkit.vision.vkp.PipelineManager.start(com.google.mlkit:vision-internal-vkp@@18.2.2:70)
E/MobileVisionBase( 9441): 	at com.google.mlkit.vision.label.custom.internal.zzf.zzf(com.google.mlkit:image-labeling-custom@@17.0.1:6)
E/MobileVisionBase( 9441): 	at com.google.mlkit.vision.label.custom.internal.zze.tryLoad(com.google.mlkit:image-labeling-custom@@17.0.1:2)
E/MobileVisionBase( 9441): 	at com.google.mlkit.common.sdkinternal.model.CustomModelLoader.load(com.google.mlkit:common@@18.1.0:3)
E/MobileVisionBase( 9441): 	at com.google.mlkit.vision.label.custom.internal.zzf.load(com.google.mlkit:image-labeling-custom@@17.0.1:2)
E/MobileVisionBase( 9441): 	at com.google.mlkit.common.sdkinternal.ModelResource.zza(com.google.mlkit:common@@18.1.0:4)
E/MobileVisionBase( 9441): 	at com.google.mlkit.common.sdkinternal.zzl.run(Unknown Source:10)
E/MobileVisionBase( 9441): 	at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@18.1.0:2)
E/MobileVisionBase( 9441): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@18.1.0:4)
E/MobileVisionBase( 9441): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(com.google.mlkit:common@@18.1.0:1)
E/MobileVisionBase( 9441): 	at com.google.mlkit.common.sdkinternal.zzi.run(Unknown Source:2)
E/MobileVisionBase( 9441): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/MobileVisionBase( 9441): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/MobileVisionBase( 9441): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(com.google.mlkit:common@@18.1.0:2)
E/MobileVisionBase( 9441): 	at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
E/MobileVisionBase( 9441): 	at java.lang.Thread.run(Thread.java:920)
E/MobileVisionBase( 9441): Caused by: java.io.FileNotFoundException: assets/ml/image_classifier.tflite
E/MobileVisionBase( 9441): 	at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
E/MobileVisionBase( 9441): 	at android.content.res.AssetManager.openFd(AssetManager.java:905)
E/MobileVisionBase( 9441): 	at com.google.mlkit.vision.vkp.PipelineManager.zzb(com.google.mlkit:vision-internal-vkp@@18.2.2:1)
E/MobileVisionBase( 9441): 	at com.google.mlkit.vision.vkp.PipelineManager.start(com.google.mlkit:vision-internal-vkp@@18.2.2:47)
```

google_ml_kit: ^0.9.0
target SDK: 30

**NOTE:** I was also getting this same error on google_ml_kit: ^0.7.3

**Comment by fbernaly** [comment]
This is was resolved in https://github.com/bharat-biradar/Google-Ml-Kit-plugin/issues/179.

And here you have the documentation: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_mlkit_image_labeling#load-local-custom-model

BTW, you need to start using `google_mlkit_image_labeling` instead of `google_ml_kit`.

More details here: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/master/packages/google_ml_kit
