### ISSUE TITLE
PlatformException on Digital Ink Recognition

### ISSUE THREAD

**Issue by Knaackee** [bharat-biradar/Google-Ml-Kit-plugin#242]
I tried this little example but got an Exception on `await _digitalInkRecognizer.recognize(i);`.

### pubspec.yaml

google_mlkit_digital_ink_recognition: ^0.2.1

Example: 

```
import 'package:google_mlkit_digital_ink_recognition/google_mlkit_digital_ink_recognition.dart'
    as MLText;
```

```
// create ink
MLText.Ink i = MLText.Ink();

// add strokes
var s1 = Stroke();
s1.points.add(StrokePoint(x: 1, y: 1, t: 1));
s1.points.add(StrokePoint(x: 2, y: 2, t: 2));
i.strokes.add(s1);

var s2 = Stroke();
s2.points.add(StrokePoint(x: 1, y: 1, t: 3));
s2.points.add(StrokePoint(x: 2, y: 2, t: 4));
i.strokes.add(s2);

// download model if not already done
MLText.DigitalInkRecognizerModelManager
    _modelManager =
    MLText.DigitalInkRecognizerModelManager();
bool exists =
    await _modelManager.isModelDownloaded(lang);
if (!exists) {
  await _modelManager.downloadModel(lang);
}

// create recognizer
MLText.DigitalInkRecognizer
    _digitalInkRecognizer =
    MLText.DigitalInkRecognizer(
        languageCode: lang);

// recognize
final candidates =
    await _digitalInkRecognizer.recognize(i);
```

Any idea? 

Thanks!

**Comment by fbernaly** [comment]
Could you share the exception log you are getting?

**Comment by Knaackee** [comment]
Here we go.

```
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at com.google_mlkit_digital_ink_recognition.DigitalInkRecognizer.handleDetection(DigitalInkRecognizer.java:73)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at com.google_mlkit_digital_ink_recognition.DigitalInkRecognizer.onMethodCall(DigitalInkRecognizer.java:36)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/MethodChannel#google_mlkit_digital_ink_recognizer( 9873): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by fbernaly** [comment]
@Knaackee : `StrokePoint.t` should be a long. that is what the exception is telling you. Also, if you go to the line where the exception is being thrown you will see that it is expecting a long: 
https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_mlkit_digital_ink_recognition/android/src/main/java/com/google_mlkit_digital_ink_recognition/DigitalInkRecognizer.java#L73

In the snippet you shared above you are passing 1, 2, 3 and 4 to `StrokePoint.t`.  In the example app you can see how we are passing a long: https://github.com/bharat-biradar/Google-Ml-Kit-plugin/blob/master/packages/google_ml_kit/example/lib/vision_detector_views/digital_ink_recognizer_view.dart#L49

When I was wrapping this plugin I found that for Dart, the equivalent for `long` in is still `int`, so, I guess other devs will have the same issue with passing int with short values. You can see what I mean here: https://stackoverflow.com/questions/57138892/dart-equivalent-of-long.

For now, make sure you pass a long to  `StrokePoint.t`, maybe is a future release we will change `t` to another data type.

**Comment by Knaackee** [comment]
Now it works as expected.

Thank you very much!
