### ISSUE TITLE
[Bug] - PlatformException in Android - Failed to init text recognizer 

### ISSUE THREAD

**Issue by Jos-Sea** [bharat-biradar/Google-Ml-Kit-plugin#385]
Getting PlatformException in Android - Failed to init text recognizer when using TextRecognitionScript.latin in constructor
and tried with TextRecognitionScript.chinese it works fine and recognise english characters.

In IOS TextRecognitionScript.latin works fine and recognise english characters.

Create an instance of TextRecognizer 

`final TextRecognizer _textRecognizer = TextRecognizer(script: TextRecognitionScript.latin);`

Android error logs - 

```
E/flutter ( 6311): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(TextRecognizerError, com.google.mlkit.common.MlKitException: Failed to init text recognizer text-recognition, null, null)
E/flutter ( 6311): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 6311): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 6311): <asynchronous suspension>
E/flutter ( 6311): #2      TextRecognizer.processImage (package:google_mlkit_text_recognition/src/text_recognizer.dart:23:20)
E/flutter ( 6311): <asynchronous suspension>
E/flutter ( 6311): #3      _TextRecognizerViewState.processImage (package:google_ml_kit_example/vision_detector_views/text_detector_view.dart:45:28)
E/flutter ( 6311): <asynchronous suspension>
E/flutter ( 6311): 
```

Plugin version - 
`google_mlkit_text_recognition: ^0.3.0`

**Comment by Jos-Sea** [comment]
Sloved adding following dependency in app -> build.gradle

```
dependencies {
    // Add language package you need to use
    implementation 'com.google.mlkit:text-recognition:16.0.0-beta5'
    //implementation 'com.google.mlkit:text-recognition-chinese:16.0.0-beta5'
    // implementation 'com.google.mlkit:text-recognition-devanagari:16.0.0-beta5'
    // implementation 'com.google.mlkit:text-recognition-japanese:16.0.0-beta5'
    // implementation 'com.google.mlkit:text-recognition-korean:16.0.0-beta5'
}
```
