### ISSUE TITLE
Custom TFlite model error running on Object Detection

### ISSUE THREAD

**Issue by WillianSalceda** [bharat-biradar/Google-Ml-Kit-plugin#58]
I've been struggling with running a custom tflite model on object detection feature. I am currently building my models through Google Colab with TFLite Model Maker, and tried with another model built following Tanner Gilbert [tutorial](https://gilberttanner.com/blog/tensorflow-object-detection-with-tensorflow-2-creating-a-custom-model).

## Expected Behavior
To work normally as it works with the default tflite model from example project.

## Current Behavior
It shows the error below (log section), and stop functioning until hot reloaded or recompiled with another model.

## To Reproduce
1. Download and extract **example** project
2. Change the default _object_labeler.tfile_ with my custom model, _model.tfile_
3. Compile and run Object Detection

## Log

```
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
Formato de par�metros incorreto -
Picked up _JAVA_OPTIONS: -Xmx4096M
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...
I/CameraManagerGlobal( 9622): Connecting to camera service
Debug service listening on ws://127.0.0.1:65309/TlaQjXuFyG4=/ws
Syncing files to device sdk gphone x86...
I/Camera  ( 9622): [FPS Range Available] is:[5, 30]
I/Camera  ( 9622): [FPS Range Available] is:[15, 30]
I/Camera  ( 9622): [FPS Range Available] is:[15, 15]
I/Camera  ( 9622): [FPS Range Available] is:[30, 30]
I/Camera  ( 9622): [FPS Range] is:[5, 30]
W/Camera  ( 9622): The selected imageFormatGroup is not supported by Android. Defaulting to yuv420
W/Gralloc4( 9622): allocator 3.x is not supported
D/TransportRuntime.JobInfoScheduler( 9622): Scheduling upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) with jobId=-843306226 in 86400000ms(Backend next call timestamp 0). Attempt 1
D/TransportRuntime.SQLiteEventStore( 9622): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler( 9622): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
D/TransportRuntime.SQLiteEventStore( 9622): Storing event with priority=DEFAULT, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler( 9622): Scheduling upload for context TransportContext(cct, DEFAULT, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) with jobId=-848286963 in 30000ms(Backend next call timestamp 1623290503699). Attempt 1
I/tflite  ( 9622): Initialized TensorFlow Lite runtime.
I/native  ( 9622): mobile_ssd_tflite_client.cc:210 Model initialized: input_size: 110592, output_locations_size: 30600, preprocessing mean value: 127.5, preprocessing std value: 127.5, inference type: 2
I/native  ( 9622): mobile_ssd_calculator.cc:113 Succeeded in initializing SSD MobileObjectLocalizerV3_1TfLiteClient
I/native  ( 9622): box_classifier_calculator.cc:125 Initializing classifier 
E/native  ( 9622): calculator_graph.cc:771 INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
E/native  ( 9622): Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf5\x01\x08\x03\x12\xc3\x01\x43\x61lculator::Open() for node \"BoxClassifierCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/native  ( 9622): pipeline_jni.cc:95 INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
E/native  ( 9622): Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf5\x01\x08\x03\x12\xc3\x01\x43\x61lculator::Open() for node \"BoxClassifierCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/native  ( 9622): pipeline_jni.cc:243 INVALID_ARGUMENT: Graph has errors: 
E/native  ( 9622): Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf5\x01\x08\x03\x12\xc3\x01\x43\x61lculator::Open() for node \"BoxClassifierCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/native  ( 9622): pipeline_jni.cc:243 INVALID_ARGUMENT: Graph has errors: 
E/native  ( 9622): Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf5\x01\x08\x03\x12\xc3\x01\x43\x61lculator::Open() for node \"BoxClassifierCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/MobileVisionBase( 9622): Error preloading model resource
E/MobileVisionBase( 9622): com.google.mlkit.common.MlKitException: Failed to initialize detector. Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).
E/MobileVisionBase( 9622): 	at com.google.mlkit.vision.vkp.PipelineManager.start(com.google.mlkit:vision-internal-vkp@@18.1.0:66)
E/MobileVisionBase( 9622): 	at com.google.mlkit.vision.objects.custom.internal.zze.tryLoad(com.google.mlkit:object-detection-custom@@16.3.2:3)
E/MobileVisionBase( 9622): 	at com.google.mlkit.common.sdkinternal.model.CustomModelLoader.load(com.google.mlkit:common@@17.1.1:3)
E/MobileVisionBase( 9622): 	at com.google.mlkit.vision.objects.custom.internal.zzf.load(com.google.mlkit:object-detection-custom@@16.3.2:2)
E/MobileVisionBase( 9622): 	at com.google.mlkit.common.sdkinternal.ModelResource.zza(Unknown Source:18)
E/MobileVisionBase( 9622): 	at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10)
E/MobileVisionBase( 9622): 	at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.1.1:2)
E/MobileVisionBase( 9622): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.1.1:4)
E/MobileVisionBase( 9622): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(Unknown Source:8)
E/MobileVisionBase( 9622): 	at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
E/MobileVisionBase( 9622): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/MobileVisionBase( 9622): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/MobileVisionBase( 9622): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(Unknown Source:10)
E/MobileVisionBase( 9622): 	at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2)
E/MobileVisionBase( 9622): 	at java.lang.Thread.run(Thread.java:923)
D/TransportRuntime.SQLiteEventStore( 9622): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler( 9622): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
I/native  ( 9622): mobile_ssd_tflite_client.cc:210 Model initialized: input_size: 110592, output_locations_size: 30600, preprocessing mean value: 127.5, preprocessing std value: 127.5, inference type: 2
I/native  ( 9622): mobile_ssd_calculator.cc:113 Succeeded in initializing SSD MobileObjectLocalizerV3_1TfLiteClient
I/native  ( 9622): box_classifier_calculator.cc:125 Initializing classifier 
E/native  ( 9622): calculator_graph.cc:771 INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
E/native  ( 9622): Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf5\x01\x08\x03\x12\xc3\x01\x43\x61lculator::Open() for node \"BoxClassifierCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/native  ( 9622): pipeline_jni.cc:95 INVALID_ARGUMENT: CalculatorGraph::Run() failed in Run: 
E/native  ( 9622): Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf5\x01\x08\x03\x12\xc3\x01\x43\x61lculator::Open() for node \"BoxClassifierCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/native  ( 9622): pipeline_jni.cc:243 INVALID_ARGUMENT: Graph has errors: 
E/native  ( 9622): Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf5\x01\x08\x03\x12\xc3\x01\x43\x61lculator::Open() for node \"BoxClassifierCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
E/native  ( 9622): pipeline_jni.cc:243 INVALID_ARGUMENT: Graph has errors: 
E/native  ( 9622): Calculator::Open() for node "BoxClassifierCalculator" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1). [type.googleapis.com/mediapipe.StatusList='\n\xf5\x01\x08\x03\x12\xc3\x01\x43\x61lculator::Open() for node \"BoxClassifierCalculator\" failed: #vk Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).\x1a+\n$tflite::support::TfLiteSupportStatus\x12\x03\x34\x30\x30']
W/System.err( 9622): com.google.mlkit.common.MlKitException: Failed to initialize detector. Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1).
W/System.err( 9622): 	at com.google.mlkit.vision.vkp.PipelineManager.start(com.google.mlkit:vision-internal-vkp@@18.1.0:66)
W/System.err( 9622): 	at com.google.mlkit.vision.objects.custom.internal.zze.tryLoad(com.google.mlkit:object-detection-custom@@16.3.2:3)
W/System.err( 9622): 	at com.google.mlkit.common.sdkinternal.model.CustomModelLoader.load(com.google.mlkit:common@@17.1.1:3)
W/System.err( 9622): 	at com.google.mlkit.vision.objects.custom.internal.zzf.load(com.google.mlkit:object-detection-custom@@16.3.2:2)
W/System.err( 9622): 	at com.google.mlkit.common.sdkinternal.ModelResource.zza(Unknown Source:18)
W/System.err( 9622): 	at com.google.mlkit.common.sdkinternal.zzn.run(Unknown Source:10)
W/System.err( 9622): 	at com.google.mlkit.common.sdkinternal.zzp.run(com.google.mlkit:common@@17.1.1:2)
W/System.err( 9622): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zze(com.google.mlkit:common@@17.1.1:4)
W/System.err( 9622): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzc(Unknown Source:8)
W/System.err( 9622): 	at com.google.mlkit.common.sdkinternal.zzj.run(Unknown Source:2)
W/System.err( 9622): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 9622): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 9622): 	at com.google.mlkit.common.sdkinternal.MlKitThreadPool.zzd(Unknown Source:10)
W/System.err( 9622): 	at com.google.mlkit.common.sdkinternal.zzk.run(Unknown Source:2)
W/System.err( 9622): 	at java.lang.Thread.run(Thread.java:923)
D/TransportRuntime.SQLiteEventStore( 9622): Storing event with priority=VERY_LOW, name=FIREBASE_ML_SDK for destination cct
D/TransportRuntime.JobInfoScheduler( 9622): Upload for context TransportContext(cct, VERY_LOW, MSRodHRwczovL2ZpcmViYXNlbG9nZ2luZy5nb29nbGVhcGlzLmNvbS92MGNjL2xvZy9iYXRjaD9mb3JtYXQ9anNvbl9wcm90bzNc) is already scheduled. Returning...
E/flutter ( 9622): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(ObjectDetectionError, com.google.mlkit.common.MlKitException: Failed to initialize detector. Unexpected number of dimensions for output index 0: got 3D, expected either 2D (BxN with B=1) or 4D (BxHxWxN with B=1, W=1, H=1)., null, null)
E/flutter ( 9622): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter ( 9622): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 9622): <asynchronous suspension>
E/flutter ( 9622): #2      ObjectDetector.processImage (package:google_ml_kit/src/vision/object_detector.dart:14:20)
E/flutter ( 9622): <asynchronous suspension>
E/flutter ( 9622): #3      _ObjectDetectorView.processImage (package:google_ml_kit_example/VisionDetectorViews/object_detector_view.dart:49:20)
E/flutter ( 9622): <asynchronous suspension>
E/flutter ( 9622): 
W/System  ( 9622): A resource failed to call release. 
```

## File
[model.zip](https://github.com/bharat-biradar/Google-Ml-Kit-plugin/files/6628046/model.zip)

**Comment by bharat-biradar** [comment]
@WillianSalceda From the error log it seems the model is not compatible with ML Kit. Not all models are compatible with ml kit there are a certain set of [criteria](https://developers.google.com/ml-kit/custom-models#model-compatibility) for it to be compatible with the API. Hope this answers your query.

**Comment by WillianSalceda** [comment]
> @WillianSalceda From the error log it seems the model is not compatible with ML Kit. Not all models are compatible with ml kit there are a certain set of [criteria](https://developers.google.com/ml-kit/custom-models#model-compatibility) for it to be compatible with the API. Hope this answers your query.

Ok... I see that it is beyond the scope of the issue, but by any chance would you be able to explain to me how to train a model that follows the criteria? I mean, is there any way to make my 3D model to 4D (or 2D)? Or just train another model that is already 4D... I am sorry, I know it's a silly question for those who understand, but I'm doing a scientific research at my university and I don't have much knowledge on TensorFlow, but I need to use it because I need a real-time object detector.

**Comment by bharat-biradar** [comment]
@WillianSalceda Sorry but I am also not familiar with working with models. But you can find pre-trained models that might be compatible from [tensorflow hub](https://tfhub.dev/s?deployment-format=lite&q=object%20detection) or read this to [create your own models](https://developers.google.com/ml-kit/custom-models#train_your_own_image_classification_model).
