### ISSUE TITLE
CocoaPods could not find compatible versions for pod "google_ml_kit"

### ISSUE THREAD

**Issue by huuthongdev** [bharat-biradar/Google-Ml-Kit-plugin#60]
I add lib to my project and run command `flutter run` on ios device. But i met a problem.

```
[!] CocoaPods could not find compatible versions for pod "google_ml_kit":
      In Podfile:
        google_ml_kit (from `.symlinks/plugins/google_ml_kit/ios`)

    Specs satisfying the `google_ml_kit (from `.symlinks/plugins/google_ml_kit/ios`)` dependency were found, but they required a higher minimum
    deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
```

**Comment by bisasuraj** [comment]
are you running this on m1 chip?

**Comment by huuthongdev** [comment]
i running on macbook intel chip

**Comment by fnoceda** [comment]
Same problem here, any solution? 
  Nombre del modelo:	MacBook Pro
  Identificador del modelo:	MacBookPro10,1
  Nombre del procesador:	Quad-Core Intel Core i7
  Velocidad del procesador:	2,3 GHz
  Cantidad de procesadores:	1
  Cantidad total de núcleos:	4
  Caché de nivel 2 (por núcleo):	256 KB
  Caché de nivel 3:	6 MB
  Tecnología Hyper-Threading:	Activado
  Memoria:	16 GB

**Comment by fbernaly** [comment]
The solution is in the logs you are getting:
```
Specs satisfying the `google_ml_kit (from `.symlinks/plugins/google_ml_kit/ios`)` dependency were found, but they required a higher minimum deployment target.
```

And in our [README](https://github.com/bharat-biradar/Google-Ml-Kit-plugin):
```
Minimum iOS Deployment Target: 10.0
```

By default Flutter creates an iOS project template with Minimum iOS Deployment Target: 9.0. You need to increase that in Xcode to at least 10.0. If you are specifying the ios version in you `Podfile` as well:

```
platform :ios, '10.0'
```
