### ISSUE TITLE
Android app crash when scanning a contact barcode

### ISSUE THREAD

**Issue by svprdga** [bharat-biradar/Google-Ml-Kit-plugin#66]
# How to reproduce
1. Create a flutter app with `google_ml_kit: ^0.6.0`
2. Implement the barcode scanning feature
3. Run it on an Android device
4. Try to scan a QR code with contact information (example attached below)

# Expected result
The lib can scan this type of code, just as it does with the other types.

# Actual result
The app crashes due to a native exception:

```
2021-06-18 12:40:15.705 13442-13442/com.example.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 13442
    java.lang.IllegalArgumentException: Unsupported value: [Ljava.lang.String;@e5c977c
        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:276)
        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:273)
        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:265)
        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:273)
        at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:265)
        at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:59)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
        at com.b.biradar.google_ml_kit.vision.BarcodeDetector$2.onSuccess(BarcodeDetector.java:207)
        at com.b.biradar.google_ml_kit.vision.BarcodeDetector$2.onSuccess(BarcodeDetector.java:85)
        at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

# Example barcode

This QR code makes the app crashes, I have tested with other QR codes that contains different kinds of contact data and the result is the same.

![Contact QR Code](https://i.ibb.co/80hwR0Z/vcard-full.png)

**Comment by bharat-biradar** [comment]
@svprdga Sorry for the delay. I have opened a PR which fixes this issue. Wait for it to be merged to master branch. Thank you for bringing it to our notice.
